- name: Configurar e verificar as m치quinas do grupo lappis
  hosts: lappis
  become: true
  become_method: su

  tasks:
    - name: Verificar conectividade com todas as m치quinas
      ansible.builtin.ping:

    - name: Instalar Nginx em todas as m치quinas
      ansible.builtin.apt:
        name: nginx
        state: present
      notify:
        - Iniciar e habilitar Nginx

    - name: Criar arquivo HTML de Ol치 Mundo nas VMs
      ansible.builtin.copy:
        dest: /var/www/html/index.html
        content: |
          <!DOCTYPE html>
          <html>
          <body>
              <h1>Ola Mundo!</h1>
              <p>To aqui pelo playbook</p>
          </body>
          </html>

  handlers:
    - name: Iniciar e habilitar Nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes